/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef simonsays_TYPES_H
#define simonsays_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





enum Color {
  RED = 1,
  YELLOW = 2,
  GREEN = 3,
  BLUE = 4
};



#endif
